/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.demo.hall;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bj=0x7f020000;
        public static final int bottom_selector=0x7f020001;
        public static final int bottom_sharp=0x7f020002;
        public static final int bottom_sharp_on=0x7f020003;
        public static final int btn=0x7f020004;
        public static final int btn_c=0x7f020005;
        public static final int dialog_btn_selector=0x7f020006;
        public static final int ic_launcher=0x7f020007;
        public static final int icon=0x7f020008;
        public static final int icon_s=0x7f020009;
        public static final int main_bg=0x7f02000a;
        public static final int pay_back=0x7f02000b;
        public static final int pay_line=0x7f02000c;
        public static final int pay_line_1=0x7f02000d;
        public static final int pay_score=0x7f02000e;
    }
    public static final class id {
        public static final int button00=0x7f050001;
        public static final int button01=0x7f050002;
        public static final int button02=0x7f050003;
        public static final int button03=0x7f050004;
        public static final int button04=0x7f050005;
        public static final int button05=0x7f050006;
        public static final int button06=0x7f050007;
        public static final int button07=0x7f050008;
        public static final int button08=0x7f050009;
        public static final int button09=0x7f05000a;
        public static final int buttonback=0x7f050000;
    }
    public static final class layout {
        public static final int goods=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int app_tip=0x7f040001;
        public static final int getting_prepayid=0x7f040002;
    }
}
